name: 🐞 Bug Report
description: Report a bug
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: | 
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe the expected behavior
      placeholder: Expected behavior...
      description: Please provide a concise description of what you were expecting to happen.
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction URL
      placeholder: https://...
      description: A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is **required**, otherwise the issue might be closed without further notice. See this post by [@antfu](https://github.com/antfu) for [*why & how?**](https://antfu.me/posts/why-reproductions-are-required).
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      placeholder: Please paste the output of `npx envinfo --system --binaries --browsers
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager.
      options:
        - npm
        - yarn
        - pnpm
        - bun
        - n/a
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue you agree to follow out [Code of Conduct](/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: contributions-guide
    attributes:
      label: Contribution Guide
      description: Before submitting this issue, please read our [Contribution Guide](/CONTRIBUTING.md)
      options:
        - label: I have read the Contributing Guide
          required: true
  - type: checkboxes
    id: validations
    attributes:
      label: Validation Steps.
      description: Before submitting this issue, ensure you have completed all the steps below
      options:
        - label: I confirm this is a bug and not a request for support or Q&A.
          required: true
        - label: I have searched existing issues to confirm this bug has not yet been reported.
          required: true
  
